@BASE_URL = http://localhost:9000

POST {{BASE_URL}}/test1.json
Content-Type: application/json

{
    "id":"POOP",
    "name":"Python OOP",
    "duration":35
}


### 其它的如下:
POST {{BASE_URL}}/test2.json
Content-Type: application/json

["React","Angular","VUE"]



### 其它的如下:
PUT {{BASE_URL}}/test3.json
Content-Type: application/json

["台新","國泰","中信"]

### 其它的如下:
PUT {{BASE_URL}}/Aproject/test0.json
Content-Type: application/json

["T1","PLG","G2"]
